CRM_RAW_FILE_MAP = {
    "crm_person.csv": "crm_party_master.csv",
    "crm_contact.csv": "crm_contact_point.csv",
    "crm_identity.csv": "crm_identity_registry.csv",
    "crm_person_address.csv": "crm_address_book.csv",
    "crm_lead.csv": "crm_lead_register.csv",
    "crm_customer.csv": "crm_customer_portfolio.csv",
    "crm_customer_lead.csv": "crm_customer_lead_bridge.csv",
    "crm_consent.csv": "crm_consent_snapshot.csv",
    "crm_marketing_preference.csv": "crm_comm_preference.csv",
    "crm_marketing_engagement.csv": "crm_campaign_touch.csv",
    "crm_account.csv": "crm_account_book.csv",
    "crm_product.csv": "crm_product_catalog.csv",
    "crm_quote.csv": "crm_quote_register.csv",
    "crm_policy.csv": "crm_policy_register.csv",
    "crm_home.csv": "crm_property_asset.csv",
    "crm_motor.csv": "crm_vehicle_asset.csv",
}


CRM_RAW_COLUMN_MAP = {
    "_batch_id": "batch_ref",
    "_extract_ts": "pull_ts",
    "_source_system": "origin_sys",
    "person_id": "party_ref",
    "person_type": "party_kind",
    "tenant_id": "tenant_cd",
    "is_lead": "lead_ind",
    "operational_paperless_consent": "paperless_ind",
    "source_id": "src_party_ref",
    "source_type": "src_party_type",
    "natural_person_id": "natural_ref",
    "first_name": "given_nm",
    "last_name": "family_nm",
    "full_name": "display_nm",
    "courtesy_title": "title_txt",
    "occupation": "occupation_txt",
    "birth_date": "dob",
    "birth_year": "birth_yr",
    "nationality": "nationality_txt",
    "gender": "gender_txt",
    "marital_status": "marital_txt",
    "assesed_disability_degree": "disability_degree",
    "preferred_language": "language_pref",
    "role": "role_txt",
    "job_title": "job_title_txt",
    "legal_person_id": "legal_ref",
    "company_name": "legal_name",
    "legal_person_score": "legal_score_no",
    "legal_person_status": "legal_status_txt",
    "legal_person_job_title": "legal_job_title_txt",
    "legal_source_id": "legal_src_ref",
    "legal_source_type": "legal_src_type",
    "date_of_constitution": "constitution_dt",
    "lead_converted_date": "lead_conv_dt",
    "contact_id": "contact_ref",
    "personal_email": "email_home_txt",
    "work_email": "email_work_txt",
    "work_phone": "phone_work_txt",
    "home_phone": "phone_home_txt",
    "identities_id": "identity_ref",
    "ecid": "ecid_txt",
    "hashed_email": "hashed_email_txt",
    "address_id": "address_ref",
    "street": "street_txt",
    "postcode": "postal_cd",
    "city": "city_nm",
    "state": "state_cd",
    "country": "country_cd",
    "lead_id": "lead_ref",
    "interested_level": "interest_bucket",
    "preferred_contact_method": "contact_pref",
    "person_score": "person_score_no",
    "person_status": "person_status_txt",
    "converted_date": "converted_dt",
    "customer_id": "customer_ref",
    "customer_number": "customer_no",
    "customer_status": "customer_status_txt",
    "customer_status_reason": "customer_status_reason_txt",
    "customer_since": "customer_since_dt",
    "customer_rating": "customer_rating_no",
    "customer_segment": "customer_segment_txt",
    "line_of_business": "lob_txt",
    "nps_score": "nps_score_no",
    "consent_id": "consent_ref",
    "opt_in_validated": "opt_in_valid_ind",
    "opt_in_legitimate_interest": "opt_in_legit_ind",
    "marketing_preference_id": "preference_ref",
    "sms": "sms_ind",
    "email": "email_ind",
    "email_subscriptions": "email_sub_ind",
    "call": "call_ind",
    "any": "any_ind",
    "commercial_email": "commercial_email_ind",
    "postal_mail": "postal_mail_ind",
    "marketing_engagement_id": "engagement_ref",
    "promotion_code": "promo_cd",
    "opened_email": "email_opened_ind",
    "marketing_status": "campaign_status_txt",
    "account_id": "account_ref",
    "account_number": "account_no",
    "account_type": "account_type_txt",
    "account_last_access": "last_access_dt",
    "account_last_change": "last_change_dt",
    "account_creation_type": "account_create_type_txt",
    "account_status": "account_status_txt",
    "product_id": "product_ref",
    "product_code": "product_cd",
    "product_type": "product_line",
    "quote_id": "quote_ref",
    "gross_revenue": "gross_amt",
    "net_revenue": "net_amt",
    "quote_number": "quote_no",
    "quote_status": "quote_status_txt",
    "renewal_amt_current_period": "renewal_amt_curr",
    "renewal_amt_next_period": "renewal_amt_next",
    "policy_id": "policy_ref",
    "cover_option": "cover_option_txt",
    "declined_claims": "declined_claim_cnt",
    "fraud_flag": "fraud_ind",
    "number_of_active_claim": "active_claim_cnt",
    "number_of_previous_claim": "previous_claim_cnt",
    "policy_cycle": "policy_cycle_no",
    "policy_end_date": "policy_end_dt",
    "policy_length": "policy_term_months",
    "policy_number": "policy_no",
    "policy_start_date": "policy_start_dt",
    "policy_status": "policy_status_txt",
    "renewal_amount_current_period": "renewal_premium_curr",
    "renewal_amount_next_period": "renewal_premium_next",
    "renewal_date": "renewal_dt",
    "sales_channel": "sales_channel_txt",
    "home_id": "property_ref",
    "wall_construction": "wall_material_txt",
    "home_risk_address": "risk_address_txt",
    "roof_construction": "roof_material_txt",
    "home_type": "property_type_txt",
    "home_state": "property_state_cd",
    "is_existing_home_customer": "existing_home_ind",
    "motor_id": "vehicle_ref",
    "auto_decline_vehicle": "auto_decline_ind",
    "body_type": "body_style_txt",
    "fuel_type": "fuel_type_txt",
    "license_status": "license_status_txt",
    "is_existing_motor_customer": "existing_motor_ind",
    "motor_lapsed_policies": "motor_lapse_cnt",
    "motor_risk_address": "garage_address_txt",
    "risk_class_code": "risk_class_cd",
    "variant": "variant_nm",
    "vehicle_owner_type": "owner_type_txt",
    "vehicle_regstate": "registration_state_cd",
    "vehicle_class": "vehicle_class_txt",
    "vehicle_model": "model_nm",
    "vehicle_type": "vehicle_type_txt",
    "motor_sum_insrd": "insured_value_amt",
    "vehicle_year": "manufacture_yr",
    "vehicle_age": "vehicle_age_yrs",
}


CRM_RAW_REVERSE_FILE_MAP = {value: key for key, value in CRM_RAW_FILE_MAP.items()}
CRM_RAW_REVERSE_COLUMN_MAP = {value: key for key, value in CRM_RAW_COLUMN_MAP.items()}


def to_crm_raw_file(canonical_file_name: str) -> str:
    return CRM_RAW_FILE_MAP[canonical_file_name]


def to_canonical_file(raw_file_name: str) -> str:
    return CRM_RAW_REVERSE_FILE_MAP[raw_file_name]


def to_crm_raw_column(canonical_column: str) -> str:
    return CRM_RAW_COLUMN_MAP[canonical_column]


def to_canonical_column(raw_column: str) -> str:
    return CRM_RAW_REVERSE_COLUMN_MAP[raw_column]
