import os
from dotenv import load_dotenv
from config.storage_paths import (
    OUTPUT_ROOT,
    RAW_ROOT,
    SYNTHETIC_BASE_ROOT,
    SILVER_API_ROOT,
)

load_dotenv()

DDL_FILE_PATH = os.getenv("DDL_FILE_PATH")
COLUMN_ATTRIBUTE_FILE = os.getenv("COLUMN_ATTRIBUTE_FILE")

PARSED_DDL_PATH = os.getenv("PARSED_DDL_PATH")
TABLE_METADATA_PATH = os.getenv("TABLE_METADATA_PATH")
ORDERED_TABLE_METADATA_PATH = os.getenv("ORDERED_TABLE_METADATA_PATH")
SYNTHETIC_DATA_JSON_PATH = os.getenv("SYNTHETIC_DATA_JSON_PATH")
CSV_OUTPUT_DIR = os.getenv("CSV_OUTPUT_DIR")

RAW_DDL = r"metadata/fixed_C360-DV.ddl"
DDL_JSON_PATH = r"metadata/table_metadata_ordered.json"
OUTPUT_BASE = OUTPUT_ROOT
SYNTHETIC_DATA = SYNTHETIC_BASE_ROOT
RAW_BASE = RAW_ROOT
SYNTHETIC_DATA_API = SILVER_API_ROOT
