CREATE TABLE IF NOT EXISTS brz_vault_metadata (
  object_type STRING,
  target_table STRING,
  source_alias STRING,
  source_table STRING,
  schema_json STRING,
  hash_alias STRING,
  hash_source_field STRING,
  business_key_target STRING,
  business_key_source STRING,
  mappings_json STRING,
  left_ref_json STRING,
  right_ref_json STRING,
  link_pk STRING,
  required_fields_json STRING,
  record_source STRING,
  process_order INT,
  is_active STRING
);

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_policy', 'policy', 'crm_policy_register', '["policy_hash_key", "load_date", "record_source", "policy_id"]', 'policy', 'policy_ref', 'policy_id', 'policy_ref', NULL, NULL, NULL, NULL, '["policy_ref"]', 'CRM', 10, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_policy', 'policy', 'crm_policy_register', '["policy_hash_key", "load_date", "cover_option", "declined_claims", "fraud_flag", "gross_revenue", "net_revenue", "number_of_active_claim", "number_of_previous_claim", "policy_cicle", "policy_end_date", "policy_length", "policy_number", "policy_start_date", "policy_status", "renewal_amount_current_period", "renewal_amount_next_period", "renewal_date", "sales_channel"]', 'policy', 'policy_ref', NULL, NULL, '{"cover_option":"cover_option_txt","declined_claims":"declined_claim_cnt","fraud_flag":"fraud_ind","gross_revenue":"gross_amt","net_revenue":"net_amt","number_of_active_claim":"active_claim_cnt","number_of_previous_claim":"previous_claim_cnt","policy_cicle":"policy_cycle_no","policy_end_date":"policy_end_dt","policy_length":"policy_term_months","policy_number":"policy_no","policy_start_date":"policy_start_dt","policy_status":"policy_status_txt","renewal_amount_current_period":"renewal_premium_curr","renewal_amount_next_period":"renewal_premium_next","renewal_date":"renewal_dt","sales_channel":"sales_channel_txt"}', NULL, NULL, NULL, '[]', 'CRM', 20, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_policy_customer', 'policy', 'crm_policy_register', '["policy_customer_hash_key", "load_date", "record_source", "policy_hash_key", "customer_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"policy","row_field":"policy_ref","column":"policy_hash_key"}', '{"hash_map":"customer","row_field":"customer_ref","column":"customer_hash_key"}', 'policy_customer_hash_key', '["policy_ref","customer_ref"]', 'CRM', 30, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_policy_product', 'policy', 'crm_policy_register', '["policy_product_hash_key", "load_date", "record_source", "policy_hash_key", "product_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"policy","row_field":"policy_ref","column":"policy_hash_key"}', '{"hash_map":"product","row_field":"product_ref","column":"product_hash_key"}', 'policy_product_hash_key', '["policy_ref","product_ref"]', 'CRM', 40, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_home', 'home', 'crm_property_asset', '["home_hash_key", "load_date", "record_source", "home_id"]', 'home', 'property_ref', 'home_id', 'property_ref', NULL, NULL, NULL, NULL, '["property_ref"]', 'CRM', 50, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_home', 'home', 'crm_property_asset', '["home_hash_key", "load_date", "wall_construction", "home_risk_address", "roof_construction", "home_type", "home_state", "is_existing_home_customer"]', 'home', 'property_ref', NULL, NULL, '{"wall_construction":"wall_material_txt","home_risk_address":"risk_address_txt","roof_construction":"roof_material_txt","home_type":"property_type_txt","home_state":"property_state_cd","is_existing_home_customer":"existing_home_ind"}', NULL, NULL, NULL, '[]', 'CRM', 60, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_product_home', 'home', 'crm_property_asset', '["product_home_hash_key", "load_date", "record_source", "product_hash_key", "home_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"product","row_field":"product_ref","column":"product_hash_key"}', '{"hash_map":"home","row_field":"property_ref","column":"home_hash_key"}', 'product_home_hash_key', '["product_ref","property_ref"]', 'CRM', 70, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_motor', 'motor', 'crm_vehicle_asset', '["motor_hash_key", "load_date", "record_source", "motor_id"]', 'motor', 'vehicle_ref', 'motor_id', 'vehicle_ref', NULL, NULL, NULL, NULL, '["vehicle_ref"]', 'CRM', 80, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_motor', 'motor', 'crm_vehicle_asset', '["motor_hash_key", "load_date", "auto_decline_vehicle", "body_type", "fuel_type", "license_status", "is_existing_motor_customer", "motor_lapsed_policies", "motor_risk_address", "risk_class_code", "variant", "vehicle_owner_type", "vehicle_regstate", "vehicle_class", "vehicle_model", "vehicle_type", "motor_sum_insrd", "vehicle_year", "vehicle_age"]', 'motor', 'vehicle_ref', NULL, NULL, '{"auto_decline_vehicle":"auto_decline_ind","body_type":"body_style_txt","fuel_type":"fuel_type_txt","license_status":"license_status_txt","is_existing_motor_customer":"existing_motor_ind","motor_lapsed_policies":"motor_lapse_cnt","motor_risk_address":"garage_address_txt","risk_class_code":"risk_class_cd","variant":"variant_nm","vehicle_owner_type":"owner_type_txt","vehicle_regstate":"registration_state_cd","vehicle_class":"vehicle_class_txt","vehicle_model":"model_nm","vehicle_type":"vehicle_type_txt","motor_sum_insrd":"insured_value_amt","vehicle_year":"manufacture_yr","vehicle_age":"vehicle_age_yrs"}', NULL, NULL, NULL, '[]', 'CRM', 90, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_product_motor', 'motor', 'crm_vehicle_asset', '["product_motor_hash_key", "load_date", "record_source", "product_hash_key", "motor_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"product","row_field":"product_ref","column":"product_hash_key"}', '{"hash_map":"motor","row_field":"vehicle_ref","column":"motor_hash_key"}', 'product_motor_hash_key', '["product_ref","vehicle_ref"]', 'CRM', 100, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_marketing_preference', 'mpr', 'crm_comm_preference', '["marketing_preference_hash_key", "load_date", "record_source", "marketing_preference_id"]', 'marketing_preference', 'preference_ref', 'marketing_preference_id', 'preference_ref', NULL, NULL, NULL, NULL, '["preference_ref","party_ref"]', 'CRM', 110, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_marketing_preference', 'mpr', 'crm_comm_preference', '["person_marketing_preference_hash_key", "load_date", "record_source", "person_hash_key", "marketing_preference_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"marketing_preference","row_field":"preference_ref","column":"marketing_preference_hash_key"}', 'person_marketing_preference_hash_key', '["party_ref","preference_ref"]', 'CRM', 120, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_marketing_preference', 'mpr', 'crm_comm_preference', '["marketing_preference_hash_key", "load_date", "sms", "email", "email_subscriptions", "call", "any", "commercial_email", "postal_mail"]', 'marketing_preference', 'preference_ref', NULL, NULL, '{"sms":"sms_ind","email":"email_ind","email_subscriptions":"email_sub_ind","call":"call_ind","any":"any_ind","commercial_email":"commercial_email_ind","postal_mail":"postal_mail_ind"}', NULL, NULL, NULL, '["party_ref","preference_ref"]', 'CRM', 130, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_marketing_engagement', 'men', 'crm_campaign_touch', '["marketing_engagement_hash_key", "load_date", "record_source", "marketing_engagement_id"]', 'marketing_engagement', 'engagement_ref', 'marketing_engagement_id', 'engagement_ref', NULL, NULL, NULL, NULL, '["engagement_ref","party_ref"]', 'CRM', 140, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_marketing_engagement', 'men', 'crm_campaign_touch', '["person_marketing_engagement_hash_key", "load_date", "record_source", "person_hash_key", "marketing_engagement_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"marketing_engagement","row_field":"engagement_ref","column":"marketing_engagement_hash_key"}', 'person_marketing_engagement_hash_key', '["party_ref","engagement_ref"]', 'CRM', 150, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_marketing_engagement', 'men', 'crm_campaign_touch', '["marketing_engagement_hash_key", "load_date", "promotion_code", "opened_email", "marketing_status"]', 'marketing_engagement', 'engagement_ref', NULL, NULL, '{"promotion_code":"promo_cd","opened_email":"email_opened_ind","marketing_status":"campaign_status_txt"}', NULL, NULL, NULL, '["party_ref","engagement_ref"]', 'CRM', 160, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_account', 'account', 'crm_account_book', '["account_hash_key", "load_date", "record_source", "account_id"]', 'account', 'account_ref', 'account_id', 'account_ref', NULL, NULL, NULL, NULL, '["account_ref","party_ref"]', 'CRM', 170, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_account', 'account', 'crm_account_book', '["person_account_hash_key", "load_date", "record_source", "person_hash_key", "account_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"account","row_field":"account_ref","column":"account_hash_key"}', 'person_account_hash_key', '["party_ref","account_ref"]', 'CRM', 180, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_account', 'account', 'crm_account_book', '["account_hash_key", "load_date", "account_number", "account_type", "account_last_access", "account_last_change", "account_creation_type", "account_status"]', 'account', 'account_ref', NULL, NULL, '{"account_number":"account_no","account_type":"account_type_txt","account_last_access":"last_access_dt","account_last_change":"last_change_dt","account_creation_type":"account_create_type_txt","account_status":"account_status_txt"}', NULL, NULL, NULL, '["party_ref","account_ref"]', 'CRM', 190, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_customer', 'customer', 'crm_customer_portfolio', '["customer_hash_key", "load_date", "record_source", "customer_id"]', 'customer', 'customer_ref', 'customer_id', 'customer_ref', NULL, NULL, NULL, NULL, '["customer_ref","party_ref"]', 'CRM', 200, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_customer_person', 'customer', 'crm_customer_portfolio', '["customer_person_hash_key", "load_date", "record_source", "customer_hash_key", "person_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"customer","row_field":"customer_ref","column":"customer_hash_key"}', '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', 'customer_person_hash_key', '["customer_ref","party_ref"]', 'CRM', 210, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_customer', 'customer', 'crm_customer_portfolio', '["customer_hash_key", "load_date", "customer_number", "customer_status", "customer_status_reason", "customer_since", "customer_rating", "customer_segment", "line_of_business", "nps_score"]', 'customer', 'customer_ref', NULL, NULL, '{"customer_number":"customer_no","customer_status":"customer_status_txt","customer_status_reason":"customer_status_reason_txt","customer_since":"customer_since_dt","customer_rating":"customer_rating_no","customer_segment":"customer_segment_txt","line_of_business":"lob_txt","nps_score":"nps_score_no"}', NULL, NULL, NULL, '["customer_ref","party_ref"]', 'CRM', 220, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_customer_lead', 'customer_lead', 'crm_customer_lead_bridge', '["customer_lead_hash_key", "load_date", "record_source", "customer_hash_key", "lead_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"customer","row_field":"customer_ref","column":"customer_hash_key"}', '{"hash_map":"lead","row_field":"lead_ref","column":"lead_hash_key"}', 'customer_lead_hash_key', '["customer_ref","lead_ref"]', 'CRM', 230, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_product', 'product', 'crm_product_catalog', '["product_hash_key", "load_date", "record_source", "product_id"]', 'product', 'product_ref', 'product_id', 'product_ref', NULL, NULL, NULL, NULL, '["product_ref"]', 'CRM', 240, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_product', 'product', 'crm_product_catalog', '["product_hash_key", "load_date", "type"]', 'product', 'product_ref', NULL, NULL, '{"type":"product_line"}', NULL, NULL, NULL, '[]', 'CRM', 250, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_quote', 'quote', 'crm_quote_register', '["quote_hash_key", "load_date", "record_source", "quote_id"]', 'quote', 'quote_ref', 'quote_id', 'quote_ref', NULL, NULL, NULL, NULL, '["quote_ref"]', 'CRM', 260, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_quote', 'quote', 'crm_quote_register', '["quote_hash_key", "load_date", "gross_revenue", "net_revenue", "quote_number", "quote_status", "renewal_amt_current_period", "renewal_amt_next_period"]', 'quote', 'quote_ref', NULL, NULL, '{"gross_revenue":"gross_amt","net_revenue":"net_amt","quote_number":"quote_no","quote_status":"quote_status_txt","renewal_amt_current_period":"renewal_amt_curr","renewal_amt_next_period":"renewal_amt_next"}', NULL, NULL, NULL, '[]', 'CRM', 270, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_quote_person', 'quote', 'crm_quote_register', '["quote_person_hash_key", "load_date", "record_source", "quote_hash_key", "person_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"quote","row_field":"quote_ref","column":"quote_hash_key"}', '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', 'quote_person_hash_key', '["quote_ref","party_ref"]', 'CRM', 280, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_quote_product', 'quote', 'crm_quote_register', '["quote_product_hash_key", "load_date", "record_source", "quote_hash_key", "product_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"quote","row_field":"quote_ref","column":"quote_hash_key"}', '{"hash_map":"product","row_field":"product_ref","column":"product_hash_key"}', 'quote_product_hash_key', '["quote_ref","product_ref"]', 'CRM', 290, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_person', 'person', 'crm_party_master', '["person_hash_key", "load_date", "record_source", "person_id"]', 'person', 'party_ref', 'person_id', 'party_ref', NULL, NULL, NULL, NULL, '["party_ref"]', 'CRM', 300, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_person', 'person', 'crm_party_master', '["person_hash_key", "load_date", "tenant_id", "is_lead", "type", "operational_paperless_consent", "source_id", "source_type"]', 'person', 'party_ref', NULL, NULL, '{"tenant_id":"tenant_cd","is_lead":"lead_ind","type":"party_kind","operational_paperless_consent":"paperless_ind","source_id":"src_party_ref","source_type":"src_party_type"}', NULL, NULL, NULL, '[]', 'CRM', 310, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_natural_person', 'person', 'crm_party_master', '["natural_person_hash_key", "load_date", "record_source", "natural_person_id"]', 'natural_person', 'natural_ref', 'natural_person_id', 'natural_ref', NULL, NULL, NULL, NULL, '["natural_ref"]', 'CRM', 320, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_natural_person', 'person', 'crm_party_master', '["person_natural_person_hash_key", "load_date", "record_source", "person_hash_key", "natural_person_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"natural_person","row_field":"natural_ref","column":"natural_person_hash_key"}', 'person_natural_person_hash_key', '["party_ref","natural_ref"]', 'CRM', 330, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_natural_person', 'person', 'crm_party_master', '["natural_person_hash_key", "load_date", "first_name", "last_name", "full_name", "courtesy_title", "occupation", "birth_date", "birth_year", "nationality", "gender", "marital_status", "assesed_disability_degree", "preferred_language", "role", "job_title"]', 'natural_person', 'natural_ref', NULL, NULL, '{"first_name":"given_nm","last_name":"family_nm","full_name":"display_nm","courtesy_title":"title_txt","occupation":"occupation_txt","birth_date":"dob","birth_year":"birth_yr","nationality":"nationality_txt","gender":"gender_txt","marital_status":"marital_txt","assesed_disability_degree":"disability_degree","preferred_language":"language_pref","role":"role_txt","job_title":"job_title_txt"}', NULL, NULL, NULL, '["natural_ref"]', 'CRM', 340, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_legal_person', 'person', 'crm_party_master', '["legal_person_hash_key", "load_date", "record_source", "legal_person_id"]', 'legal_person', 'legal_ref', 'legal_person_id', 'legal_ref', NULL, NULL, NULL, NULL, '["legal_ref"]', 'CRM', 350, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_legal_person', 'person', 'crm_party_master', '["person_legal_person_hash_key", "load_date", "record_source", "person_hash_key", "legal_person_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"legal_person","row_field":"legal_ref","column":"legal_person_hash_key"}', 'person_legal_person_hash_key', '["party_ref","legal_ref"]', 'CRM', 360, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_legal_person', 'person', 'crm_party_master', '["legal_person_hash_key", "load_date", "person_score", "job_title", "source_id", "source_type", "person_status", "converted_date", "date_of_constitution", "company_name"]', 'legal_person', 'legal_ref', NULL, NULL, '{"person_score":"legal_score_no","job_title":"legal_job_title_txt","source_id":"legal_src_ref","source_type":"legal_src_type","person_status":"legal_status_txt","converted_date":"lead_conv_dt","date_of_constitution":"constitution_dt","company_name":"legal_name"}', NULL, NULL, NULL, '["legal_ref"]', 'CRM', 370, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_contact', 'contact', 'crm_contact_point', '["contact_hash_key", "load_date", "record_source", "contact_id"]', 'contact', 'contact_ref', 'contact_id', 'contact_ref', NULL, NULL, NULL, NULL, '["contact_ref","party_ref"]', 'CRM', 380, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_contact', 'contact', 'crm_contact_point', '["person_contact_hash_key", "load_date", "record_source", "person_hash_key", "contact_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"contact","row_field":"contact_ref","column":"contact_hash_key"}', 'person_contact_hash_key', '["party_ref","contact_ref"]', 'CRM', 390, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_contact', 'contact', 'crm_contact_point', '["contact_hash_key", "load_date", "personal_email", "work_email", "work_phone", "home_phone"]', 'contact', 'contact_ref', NULL, NULL, '{"personal_email":"email_home_txt","work_email":"email_work_txt","work_phone":"phone_work_txt","home_phone":"phone_home_txt"}', NULL, NULL, NULL, '["party_ref","contact_ref"]', 'CRM', 400, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_identities', 'identity', 'crm_identity_registry', '["identities_hash_key", "load_date", "record_source", "identities_id"]', 'identities', 'identity_ref', 'identities_id', 'identity_ref', NULL, NULL, NULL, NULL, '["identity_ref","party_ref"]', 'CRM', 410, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_identities', 'identity', 'crm_identity_registry', '["person_identities_hash_key", "load_date", "record_source", "person_hash_key", "identities_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"identities","row_field":"identity_ref","column":"identities_hash_key"}', 'person_identities_hash_key', '["party_ref","identity_ref"]', 'CRM', 420, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_identities', 'identity', 'crm_identity_registry', '["identities_hash_key", "load_date", "ecid", "hashed_email"]', 'identities', 'identity_ref', NULL, NULL, '{"ecid":"ecid_txt","hashed_email":"hashed_email_txt"}', NULL, NULL, NULL, '["party_ref","identity_ref"]', 'CRM', 430, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_home_address', 'address', 'crm_address_book', '["home_address_hash_key", "load_date", "record_source", "home_address_id"]', 'home_address', 'address_ref', 'home_address_id', 'address_ref', NULL, NULL, NULL, NULL, '["address_ref","party_ref"]', 'CRM', 440, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_home_address', 'address', 'crm_address_book', '["person_home_address_hash_key", "load_date", "record_source", "person_hash_key", "home_address_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"home_address","row_field":"address_ref","column":"home_address_hash_key"}', 'person_home_address_hash_key', '["party_ref","address_ref"]', 'CRM', 450, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_home_address', 'address', 'crm_address_book', '["home_address_hash_key", "load_date", "street", "postcode", "city", "state", "country"]', 'home_address', 'address_ref', NULL, NULL, '{"street":"street_txt","postcode":"postal_cd","city":"city_nm","state":"state_cd","country":"country_cd"}', NULL, NULL, NULL, '["party_ref","address_ref"]', 'CRM', 460, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_lead', 'lead', 'crm_lead_register', '["lead_hash_key", "load_date", "record_source", "lead_id"]', 'lead', 'lead_ref', 'lead_id', 'lead_ref', NULL, NULL, NULL, NULL, '["lead_ref","party_ref"]', 'CRM', 470, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_lead', 'lead', 'crm_lead_register', '["person_lead_hash_key", "load_date", "record_source", "person_hash_key", "lead_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"lead","row_field":"lead_ref","column":"lead_hash_key"}', 'person_lead_hash_key', '["party_ref","lead_ref"]', 'CRM', 480, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_lead', 'lead', 'crm_lead_register', '["lead_hash_key", "load_date", "interested_level", "preferred_contact_method", "person_score", "person_status", "converted_date"]', 'lead', 'lead_ref', NULL, NULL, '{"interested_level":"interest_bucket","preferred_contact_method":"contact_pref","person_score":"person_score_no","person_status":"person_status_txt","converted_date":"converted_dt"}', NULL, NULL, NULL, '["party_ref","lead_ref"]', 'CRM', 490, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('hub', 'hub_consent', 'consent', 'crm_consent_snapshot', '["consent_hash_key", "load_date", "record_source", "consent_id"]', 'consent', 'consent_ref', 'consent_id', 'consent_ref', NULL, NULL, NULL, NULL, '["consent_ref","party_ref"]', 'CRM', 500, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('link', 'link_person_consent', 'consent', 'crm_consent_snapshot', '["person_consent_hash_key", "load_date", "record_source", "person_hash_key", "consent_hash_key"]', NULL, NULL, NULL, NULL, NULL, '{"hash_map":"person","row_field":"party_ref","column":"person_hash_key"}', '{"hash_map":"consent","row_field":"consent_ref","column":"consent_hash_key"}', 'person_consent_hash_key', '["party_ref","consent_ref"]', 'CRM', 510, 'Y');

INSERT INTO brz_vault_metadata (object_type, target_table, source_alias, source_table, schema_json, hash_alias, hash_source_field, business_key_target, business_key_source, mappings_json, left_ref_json, right_ref_json, link_pk, required_fields_json, record_source, process_order, is_active)
VALUES ('sat', 'sat_consent', 'consent', 'crm_consent_snapshot', '["consent_hash_key", "load_date", "opt_in_validated", "opt_in_legitimate_interest"]', 'consent', 'consent_ref', NULL, NULL, '{"opt_in_validated":"opt_in_valid_ind","opt_in_legitimate_interest":"opt_in_legit_ind"}', NULL, NULL, NULL, '["party_ref","consent_ref"]', 'CRM', 520, 'Y');
